package com.ws101.busa.balading.ecommerceapiv2.model;

import jakarta.persistence.*;
import java.util.List;

/**
 * JPA Entity representing a product category in the database.
 * Maps to the 'categories' table.
 * One category can have multiple products.
 */
@Entity
@Table(name = "categories")
public class Category {

    /**
     * Unique identifier for the category.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the category. Must be unique and cannot be null.
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * List of products belonging to this category.
     * Mapped by the 'category' field in the Product entity.
     * Cascade ALL ensures product operations cascade to category.
     * orphanRemoval=true deletes products when removed from list.
     */
    @OneToMany(mappedBy = "category", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Product> products;

    /**
     * Default constructor required by JPA.
     */
    public Category() {
    }

    /**
     * Constructor for creating a category with a name.
     * @param name the category name
     */
    public Category(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Product> getProducts() {
        return products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }
}