package com.ws101.busa.balading.ecommerceapiv2.model;

import jakarta.persistence.*;

/**
 * JPA Entity representing a product in the database.
 * Maps to the 'products' table.
 * Each product belongs to one category.
 */
@Entity
@Table(name = "products")
public class Product {

    /**
     * Unique identifier for the product.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product. Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Price of the product. Supports decimal values.
     * Cannot be null.
     */
    @Column(nullable = false)
    private Double price;

    /**
     * Category that this product belongs to.
     * Many products can belong to one category.
     * Uses LAZY loading to improve performance.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category category;

    /**
     * Default constructor required by JPA.
     */
    public Product() {
    }

    /**
     * Constructor for creating a product with name and price.
     * @param name the product name
     * @param price the product price
     */
    public Product(String name, Double price) {
        this.name = name;
        this.price = price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }
}