package com.ws101.busa.balading.ecommerceapiv2.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.EqualsAndHashCode;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity representing a product in the e-commerce system.
 *
 * Contains product details such as name, description, price, category, and stock quantity.
 * Includes validation constraints and automatic timestamp management.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode
@Entity
@Table(name = "products")
public class Product {

    /**
     * Unique identifier for the product.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Product name. Required field with minimum length validation.
     * Must not be blank and cannot exceed 100 characters.
     */
    @NotBlank(message = "Name cannot be empty")
    @Size(max = 100, message = "Name must not exceed 100 characters")
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Detailed description of the product.
     * Optional field stored as TEXT in the database.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Product price. Must be greater than 0.
     * Supports up to 8 digits and 2 decimal places.
     */
    @NotNull(message = "Price is required")
    @Positive(message = "Price must be greater than 0")
    @Digits(integer = 8, fraction = 2, message = "Price must have max 8 digits and 2 decimal places")
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    /**
     * Product category. Required field.
     * Cannot be blank and cannot exceed 50 characters.
     */
    @NotBlank(message = "Category cannot be empty")
    @Size(max = 50, message = "Category must not exceed 50 characters")
    @Column(nullable = false, length = 50)
    private String category;

    /**
     * Available stock quantity for the product.
     * Must be non-negative.
     */
    @NotNull(message = "Stock quantity is required")
    @Min(value = 0, message = "Stock quantity cannot be negative")
    @Column(nullable = false)
    private Integer stockQuantity;

    /**
     * URL of the product image.
     * Optional field.
     */
    @Column(name = "image_url")
    private String imageUrl;

    /**
     * Timestamp when the product was created.
     * Automatically set on creation and not updatable.
     */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the product was last updated.
     * Automatically updated on each modification.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Sets createdAt and updatedAt timestamps before persisting the entity.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * Updates the updatedAt timestamp before updating the entity.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}